name: CI, Build & Process PayPal Payment

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  repository_dispatch:
    types: [ paypal-payment ]

jobs:
  build:
    if: ${{ github.event_name != 'repository_dispatch' }}
    runs-on: ubuntu-latest
    env:
      VITE_PAYPAL_CLIENT_ID: ${{ secrets.VITE_PAYPAL_CLIENT_ID }}
      VITE_PAYPAL_SECRET: ${{ secrets.VITE_PAYPAL_SECRET }}
      VITE_SUPABASE_KEY: ${{ secrets.VITE_SUPABASE_KEY }}
      VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: Criar arquivo .env dinâmico para o Frontend
        run: |
          echo "VITE_PAYPAL_CLIENT_ID=${VITE_PAYPAL_CLIENT_ID}" > .env
          echo "VITE_PAYPAL_SECRET=${VITE_PAYPAL_SECRET}" >> .env
          echo "VITE_SUPABASE_KEY=${VITE_SUPABASE_KEY}" >> .env
          echo "VITE_SUPABASE_URL=${VITE_SUPABASE_URL}" >> .env

      - name: Instalar Dependências
        run: npm ci

      - name: Build do Projeto
        run: npm run build --if-present

      - name: Executar Testes
        run: npm test

    

  process_paypal:
    if: ${{ github.event_name == 'repository_dispatch' && github.event.action == 'paypal-payment' }}
    runs-on: ubuntu-latest
    env:
      SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
      SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Processar Pagamento do PayPal e Inserir Reserva no Supabase
        run: |
          curl -X POST "$SUPABASE_URL/rest/v1/reservations" \
            -H "apikey: $SUPABASE_SERVICE_KEY" \
            -H "Authorization: Bearer $SUPABASE_SERVICE_KEY" \
            -H "Content-Type: application/json" \
            -d '{
              "user_id": "${{ github.event.client_payload.user_id }}",
              "check_in": "${{ github.event.client_payload.check_in }}",
              "check_out": "${{ github.event.client_payload.check_out }}",
              "room_id": "${{ github.event.client_payload.room_id }}",
              "payment_status": "completed",
              "status": "confirmada"
            }'
